export const certifications = [
  {
    slug: "junior-web-programmer-bnsp",
    name: "Junior Web Programmer",
    issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
    issuerUrl: null,
    issuedAt: "2026-06",
    expiresAt: "2030-06",
    credentialId: null,
    credentialUrl: null,
    image: null,
    pdf: null,
    skills: ["Web Development"],
    description: null,
    featured: true,
  },
  {
    slug: "english-proficiency-test-upn",
    name: "English Proficiency Test",
    issuer: "Pusat Bahasa UPN \"Veteran\" Jawa Timur",
    issuerUrl: null,
    issuedAt: "2026-06",
    expiresAt: "2028-06",
    credentialId: null,
    credentialUrl: null,
    image: null,
    pdf: null,
    skills: ["English Proficiency"],
    description: null,
    featured: true,
  },
  {
    slug: "microsoft-office-office-staff-skill-academy",
    name: "Microsoft Office for Office Staff",
    issuer: "Skill Academy by Ruangguru",
    issuerUrl: null,
    issuedAt: "2024-07",
    expiresAt: "2028-07",
    credentialId: null,
    credentialUrl: null,
    image: null,
    pdf: null,
    skills: ["Microsoft Office"],
    description: null,
    featured: false,
  },
  {
    slug: "mobile-development-uiux-infinite-learning",
    name: "Mobile Development & UI/UX Design",
    issuer: "Infinite Learning",
    issuerUrl: null,
    issuedAt: "2024-09",
    expiresAt: "2024-12",
    credentialId: null,
    credentialUrl: null,
    image: null,
    pdf: null,
    skills: ["Mobile Development", "UI/UX Design"],
    description: null,
    featured: false,
  },
  {
    slug: "mini-bootcamp-web-development-edspert",
    name: "Mini Bootcamp - Web Development",
    issuer: "Edspert.id",
    issuerUrl: null,
    issuedAt: "2024-02",
    expiresAt: null,
    credentialId: null,
    credentialUrl: null,
    image: null,
    pdf: null,
    skills: ["Web Development"],
    description: null,
    featured: false,
  },
];
