export const experience = [
  {
    id: "it-staff-dp3appkb",
    placeholder: false,
    company: "Dinas Pemberdayaan Perempuan dan Perlindungan Anak serta Pengendalian Penduduk dan Keluarga Berencana (DP3APPKB)",
    companyUrl: null,
    role: { id: "IT Staff", en: "IT Staff" },
    employmentType: null,
    location: "Surabaya, Indonesia",
    remote: false,
    startDate: "2025-04",
    endDate: "2026-06",
    current: false,
    summary: {
      id: "Profesional IT Support dengan pengalaman langsung dalam memberikan dukungan teknis, troubleshooting, pemeliharaan perangkat, dan implementasi sistem. Berpengalaman dalam memberikan dukungan kepada 30 pengguna serta melakukan pemeliharaan 20 komputer dan perangkat IT untuk memastikan operasional sehari-hari berjalan dengan andal, aman, dan efisien. Memiliki kemampuan dalam menangani masalah hardware dan software, memelihara infrastruktur IT, serta mendukung pembaruan sistem.",
      en: "IT Support professional with hands-on experience in providing technical support, troubleshooting, device maintenance, and system implementation. Experienced in supporting 30 users and maintaining 20 computers and IT devices to ensure reliable, secure, and efficient daily operations. Skilled in resolving technical issues, maintaining IT infrastructure, and supporting system updates.",
    },
    responsibilities: {
      id: [
        "- Memberikan dukungan teknis dan troubleshooting kepada 30 pengguna untuk meminimalkan gangguan pekerjaan dan menjaga kelancaran operasional IT sehari-hari.",
        "- Melakukan pemeliharaan, konfigurasi, dan pemantauan terhadap 20 komputer dan perangkat IT untuk memastikan keandalan serta performa perangkat.",
        "- Mendiagnosis dan menyelesaikan masalah hardware dan software yang berulang.",
        "- Mendukung proses pembaruan sistem, instalasi software, dan kegiatan implementasi IT.",
        "- Melakukan pemeliharaan rutin untuk memastikan perangkat dan sistem IT tetap stabil, aman, dan siap digunakan dalam kegiatan operasional sehari-hari.",
      ],
      en: [
        "- Provided technical support and troubleshooting for 30 users to minimize work disruptions and maintain smooth daily IT operations.",
        "- Maintained, configured, and monitored 20 computers and IT devices to ensure reliability and optimal performance.",
        "- Diagnosed and resolved recurring hardware and software issues.",
        "- Supported system updates, software installation, and IT implementation activities.",
        "- Performed routine maintenance to keep IT devices and systems stable, secure, and ready for daily use.",
      ],
    },
    achievements: { id: [], en: [] },
    measurableOutcomes: { id: [], en: [] },
    technologies: ["IT Operations", "Troubleshooting", "System Maintenance", "Technical Support"],
    relatedProjectSlug: null,
  },
  {
    id: "full-stack-developer-winnicode",
    placeholder: false,
    company: "PT. Winnicode Garuda Teknologi",
    companyUrl: null,
    role: { id: "Full Stack Developer", en: "Full Stack Developer" },
    employmentType: null,
    location: "Bandung, Indonesia",
    remote: true,
    startDate: "2025-02",
    endDate: "2025-07",
    current: false,
    summary: {
      id: "Web Developer dengan pengalaman dalam mengembangkan dan memelihara sistem absensi karyawan berbasis web menggunakan Laravel, PHP, dan MySQL. Mengembangkan sistem yang mendukung 50 karyawan dengan fitur clock-in/clock-out digital, pencatatan dan pelacakan kehadiran, pencatatan absensi otomatis, autentikasi, pelaporan, serta manajemen data. Berpengalaman dalam seluruh proses pengembangan sistem, mulai dari analisis kebutuhan, pengembangan, pengujian, hingga implementasi.",
      en: "Web Developer with hands-on experience in developing and maintaining a web-based employee attendance system using Laravel, PHP, and MySQL. Developed a system supporting 50 employees with digital clock-in/clock-out, attendance tracking, automated attendance records, authentication, reporting, and data management features. Experienced across the software development lifecycle, from requirements analysis and development to testing and implementation.",
    },
    responsibilities: {
      id: [
        "- Mengembangkan dan memelihara sistem absensi karyawan berbasis web menggunakan Laravel, PHP, dan MySQL untuk 50 karyawan.",
        "- Mengimplementasikan fitur clock-in/clock-out digital, pelacakan kehadiran, pencatatan absensi harian otomatis, dan manajemen data karyawan.",
        "- Mengembangkan fitur autentikasi, integrasi database, pelaporan, dan manajemen data untuk mengelola ratusan data absensi.",
        "- Mengurangi ketergantungan pada proses absensi manual dengan mendigitalisasi pencatatan kehadiran dan meningkatkan aksesibilitas data.",
        "- Melakukan analisis kebutuhan, pengembangan, pengujian, dan implementasi sistem dalam proses pengembangan aplikasi.",
        "- Mengidentifikasi, melakukan troubleshooting, dan menyelesaikan masalah fungsional sebelum deployment untuk meningkatkan keandalan aplikasi dan pengalaman pengguna.",
      ],
      en: [
        "- Developed and maintained a web-based employee attendance system using Laravel, PHP, and MySQL for 50 employees.",
        "- Implemented digital clock-in/clock-out, attendance tracking, automated daily attendance records, and employee data management features.",
        "- Developed authentication, database integration, reporting, and data-management functionalities to handle hundreds of attendance records.",
        "- Reduced reliance on manual attendance processing by digitizing attendance recording and improving data accessibility.",
        "- Conducted requirements analysis, development, testing, and implementation throughout the system development process.",
        "- Identified, troubleshot, and resolved functional issues before deployment to improve application reliability and user experience.",
      ],
    },
    achievements: { id: [], en: [] },
    measurableOutcomes: { id: [], en: [] },
    technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "HTML", "CSS"],
    relatedProjectSlug: "employee-attendance-system",
  },
  {
    id: "Android-ui/ux-developer-infinite",
    placeholder: false,
    company: "Infinite Learning",
    companyUrl: null,
    role: { id: "Android Mobile Development & UI/UX Design", en: "Android Mobile Development & UI/UX Design" },
    employmentType: null,
    location: "Batam, Indonesia",
    remote: true,
    startDate: "2024-09",
    endDate: "2024-12",
    current: false,
    summary: {
      id: "Mobile Application Developer dengan pengalaman dalam pengembangan aplikasi Android menggunakan Kotlin dan Jetpack Compose, serta desain UI/UX menggunakan Figma. Berpengalaman dalam mengimplementasikan antarmuka mobile, navigasi, dan fungsionalitas aplikasi, serta menerapkan pendekatan user-centered design melalui pembuatan wireframe, prototype, dan usability testing. Memahami perencanaan proyek, pemantauan progres, dan kolaborasi selama proses desain dan pengembangan aplikasi.",
      en: "Mobile Application Developer with hands-on experience in Android development using Kotlin and Jetpack Compose, as well as UI/UX design using Figma. Experienced in implementing mobile interfaces, navigation, and application functionality, while applying user-centered design through wireframing, prototyping, and usability testing. Familiar with project planning, progress tracking, and cross-functional collaboration throughout the design and development process.",
    },
    responsibilities: {
      id: [
        "- Mengembangkan aplikasi Android menggunakan Kotlin dan Jetpack Compose, termasuk implementasi UI, navigasi, dan fungsionalitas dasar aplikasi.",
        "- Mendesain antarmuka aplikasi mobile menggunakan Figma dengan menghasilkan 5 wireframe, 3 interactive prototype, dan 3 high-fidelity design.",
        "- Melakukan 10 sesi usability testing dan menerapkan 3 iterasi desain berdasarkan feedback pengguna untuk meningkatkan navigasi, tata letak, dan usability aplikasi.",
        "- Merencanakan tugas proyek, mengoordinasikan aktivitas, dan memantau progres pengembangan selama proses pengerjaan proyek.",
        "- Menerapkan prinsip project management untuk mendukung kolaborasi yang efektif antara proses desain dan pengembangan.",
      ],
      en: [
        "- Designed mobile application interfaces using Figma, creating 5 wireframes, 3 interactive prototypes, and 3 high-fidelity designs.",
        "- Developed Android applications using Kotlin and Jetpack Compose, including UI implementation, navigation, and basic application functionality.",
        "- Conducted 10 usability testing sessions and implemented 3 design iterations based on user feedback to improve navigation, layout, and overall usability.",
        "- Planned project tasks, coordinated activities, and tracked development progress throughout the project lifecycle.",
        "- Applied project management principles to support effective collaboration between design and development activities.",
      ],
    },
    achievements: { id: [], en: [] },
    measurableOutcomes: { id: [], en: [] },
    technologies: ["Jetpack Compose", "Kotlin", "Firebase", "Figma"],
    relatedProjectSlug: "wiserrapp-swiftlet-farming",
  },
];
