export const experience = [
  {
    id: "it-staff-dp3appkb",
    placeholder: false,
    company: "Dinas Pemberdayaan Perempuan dan Perlindungan Anak serta Pengendalian Penduduk dan Keluarga Berencana (DP3APPKB)",
    companyUrl: null,
    role: { id: "IT Staff", en: "IT Staff" },
    employmentType: null,
    location: "Surabaya, Indonesia",
    remote: false,
    startDate: "2025-04",
    endDate: "2026-06",
    current: false,
    summary: {
      id: "Profesional IT Support dengan pengalaman langsung dalam memberikan dukungan teknis, troubleshooting, pemeliharaan perangkat, dan implementasi sistem. Berpengalaman dalam memberikan dukungan kepada 30 pengguna serta melakukan pemeliharaan 20 komputer dan perangkat IT untuk memastikan operasional sehari-hari berjalan dengan andal, aman, dan efisien. Memiliki kemampuan dalam menangani masalah hardware dan software, memelihara infrastruktur IT, serta mendukung pembaruan sistem.",
      en: "IT Support professional with hands-on experience in providing technical support, troubleshooting, device maintenance, and system implementation. Experienced in supporting 30 users and maintaining 20 computers and IT devices to ensure reliable, secure, and efficient daily operations. Skilled in resolving technical issues, maintaining IT infrastructure, and supporting system updates.",
    },
    responsibilities: {
      id: [
        "- Memberikan dukungan teknis dan troubleshooting kepada 30 pengguna untuk meminimalkan gangguan pekerjaan dan menjaga kelancaran operasional IT sehari-hari.",
        "- Melakukan pemeliharaan, konfigurasi, dan pemantauan terhadap 20 komputer dan perangkat IT untuk memastikan keandalan serta performa perangkat.",
        "- Mendiagnosis dan menyelesaikan masalah hardware dan software yang berulang.",
        "- Mendukung proses pembaruan sistem, instalasi software, dan kegiatan implementasi IT.",
        "- Melakukan pemeliharaan rutin untuk memastikan perangkat dan sistem IT tetap stabil, aman, dan siap digunakan dalam kegiatan operasional sehari-hari.",
      ],
      en: [
        "- Provided technical support and troubleshooting for 30 users to minimize work disruptions and maintain smooth daily IT operations.",
        "- Maintained, configured, and monitored 20 computers and IT devices to ensure reliability and optimal performance.",
        "- Diagnosed and resolved recurring hardware and software issues.",
        "- Supported system updates, software installation, and IT implementation activities.",
        "- Performed routine maintenance to keep IT devices and systems stable, secure, and ready for daily use.",
      ],
    },
    achievements: { id: [], en: [] },
    measurableOutcomes: { id: [], en: [] },
    technologies: ["IT Operations", "Troubleshooting", "System Maintenance", "Technical Support"],
    relatedProjectSlug: null,
  },
  {
    id: "full-stack-developer-winnicode",
    placeholder: false,
    company: "PT. Winnicode Garuda Teknologi",
    companyUrl: null,
    role: { id: "Full Stack Developer", en: "Full Stack Developer" },
    employmentType: null,
    location: "Bandung, Indonesia",
    remote: true,
    startDate: "2025-02",
    endDate: "2025-07",
    current: false,
    summary: {
      id: "Web Developer dengan pengalaman dalam mengembangkan dan memelihara sistem absensi karyawan berbasis web menggunakan Laravel, PHP, dan MySQL. Mengembangkan sistem yang mendukung 50 karyawan dengan fitur clock-in/clock-out digital, pencatatan dan pelacakan kehadiran, pencatatan absensi otomatis, autentikasi, pelaporan, serta manajemen data. Berpengalaman dalam seluruh proses pengembangan sistem, mulai dari analisis kebutuhan, pengembangan, pengujian, hingga implementasi.",
      en: "Web Developer with hands-on experience in developing and maintaining a web-based employee attendance system using Laravel, PHP, and MySQL. Developed a system supporting 50 employees with digital clock-in/clock-out, attendance tracking, automated attendance records, authentication, reporting, and data management features. Experienced across the software development lifecycle, from requirements analysis and development to testing and implementation.",
    },
    responsibilities: {
      id: [
        "- Mengembangkan dan memelihara sistem absensi karyawan berbasis web menggunakan Laravel, PHP, dan MySQL untuk 50 karyawan.",
        "- Mengimplementasikan fitur clock-in/clock-out digital, pelacakan kehadiran, pencatatan absensi harian otomatis, dan manajemen data karyawan.",
        "- Mengembangkan fitur autentikasi, integrasi database, pelaporan, dan manajemen data untuk mengelola ratusan data absensi.",
        "- Mengurangi ketergantungan pada proses absensi manual dengan mendigitalisasi pencatatan kehadiran dan meningkatkan aksesibilitas data.",
        "- Melakukan analisis kebutuhan, pengembangan, pengujian, dan implementasi sistem dalam proses pengembangan aplikasi.",
        "- Mengidentifikasi, melakukan troubleshooting, dan menyelesaikan masalah fungsional sebelum deployment untuk meningkatkan keandalan aplikasi dan pengalaman pengguna.",
      ],
      en: [
        "- Developed and maintained a web-based employee attendance system using Laravel, PHP, and MySQL for 50 employees.",
        "- Implemented digital clock-in/clock-out, attendance tracking, automated daily attendance records, and employee data management features.",
        "- Developed authentication, database integration, reporting, and data-management functionalities to handle hundreds of attendance records.",
        "- Reduced reliance on manual attendance processing by digitizing attendance recording and improving data accessibility.",
        "- Conducted requirements analysis, development, testing, and implementation throughout the system development process.",
        "- Identified, troubleshot, and resolved functional issues before deployment to improve application reliability and user experience.",
      ],
    },
    achievements: { id: [], en: [] },
    measurableOutcomes: { id: [], en: [] },
    technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "HTML", "CSS"],
    relatedProjectSlug: "employee-attendance-system",
  },
  {
    id: "Android-ui/ux-developer-infinite",
    placeholder: false,
    company: "PT. Winnicode Garuda Teknologi",
    companyUrl: null,
    role: { id: "Full Stack Developer", en: "Full Stack Developer" },
    employmentType: null,
    location: "Bandung, Indonesia",
    remote: true,
    startDate: "2025-02",
    endDate: "2025-07",
    current: false,
    summary: {
      id: "Web Developer dengan pengalaman dalam mengembangkan dan memelihara sistem absensi karyawan berbasis web menggunakan Laravel, PHP, dan MySQL. Mengembangkan sistem yang mendukung 50 karyawan dengan fitur clock-in/clock-out digital, pencatatan dan pelacakan kehadiran, pencatatan absensi otomatis, autentikasi, pelaporan, serta manajemen data. Berpengalaman dalam seluruh proses pengembangan sistem, mulai dari analisis kebutuhan, pengembangan, pengujian, hingga implementasi.",
      en: "Web Developer with hands-on experience in developing and maintaining a web-based employee attendance system using Laravel, PHP, and MySQL. Developed a system supporting 50 employees with digital clock-in/clock-out, attendance tracking, automated attendance records, authentication, reporting, and data management features. Experienced across the software development lifecycle, from requirements analysis and development to testing and implementation.",
    },
    responsibilities: {
      id: [
        "- Mengembangkan dan memelihara sistem absensi karyawan berbasis web menggunakan Laravel, PHP, dan MySQL untuk 50 karyawan.",
        "- Mengimplementasikan fitur clock-in/clock-out digital, pelacakan kehadiran, pencatatan absensi harian otomatis, dan manajemen data karyawan.",
        "- Mengembangkan fitur autentikasi, integrasi database, pelaporan, dan manajemen data untuk mengelola ratusan data absensi.",
        "- Mengurangi ketergantungan pada proses absensi manual dengan mendigitalisasi pencatatan kehadiran dan meningkatkan aksesibilitas data.",
        "- Melakukan analisis kebutuhan, pengembangan, pengujian, dan implementasi sistem dalam proses pengembangan aplikasi.",
        "- Mengidentifikasi, melakukan troubleshooting, dan menyelesaikan masalah fungsional sebelum deployment untuk meningkatkan keandalan aplikasi dan pengalaman pengguna.",
      ],
      en: [
        "- Developed and maintained a web-based employee attendance system using Laravel, PHP, and MySQL for 50 employees.",
        "- Implemented digital clock-in/clock-out, attendance tracking, automated daily attendance records, and employee data management features.",
        "- Developed authentication, database integration, reporting, and data-management functionalities to handle hundreds of attendance records.",
        "- Reduced reliance on manual attendance processing by digitizing attendance recording and improving data accessibility.",
        "- Conducted requirements analysis, development, testing, and implementation throughout the system development process.",
        "- Identified, troubleshot, and resolved functional issues before deployment to improve application reliability and user experience.",
      ],
    },
    achievements: { id: [], en: [] },
    measurableOutcomes: { id: [], en: [] },
    technologies: ["Laravel", "PHP", "MySQL", "JavaScript", "HTML", "CSS"],
    relatedProjectSlug: "employee-attendance-system",
  },
];
