export const projects = [
  {
    slug: "prognosis-chronic-lymphocytic-leukemia",
    placeholder: false,
    title: {
      id: "Prognosis for Chronic Lymphocytic Leukemia",
      en: "Prognosis for Chronic Lymphocytic Leukemia",
    },
    shortTitle: { id: "CLL Prognosis", en: "CLL Prognosis" },
    year: "2026",
    startDate: "2026-07",
    endDate: "2026-07",
    status: { id: "Selesai", en: "Completed" },
    featured: true,
    role: { id: "Machine Learning Developer", en: "Machine Learning Developer" },
    projectType: { id: "Machine Learning / Computer Vision", en: "Machine Learning / Computer Vision" },
    teamContext: null,
    company: null,
    client: null,
    links: { liveUrl: null, repositoryUrl: null, documentationUrl: null },
    technology: {
      stack: ["Swin Transformer", "Streamlit"],
      tools: ["Image Classification", "Model Evaluation"],
    },
    media: {
      cover: "/image/thumbnail leukemia.png",
      thumbnail: "/image/mockup leukemia.png",
      coverAlt: {
        id: "Visual placeholder untuk project Prognosis for Chronic Lymphocytic Leukemia.",
        en: "Visual placeholder for the Prognosis for Chronic Lymphocytic Leukemia project.",
      },
      screenshots: [],
      gallery: [],
      ogImage: null,
    },
    caseStudy: {
      summary: {
        id: "Model Swin Transformer untuk mengklasifikasikan 10.216 citra sel darah putih menjadi Normal dan Chronic Lymphocytic Leukemia (CLL), dengan akurasi 86,96% dan deployment melalui aplikasi Streamlit interaktif.",
        en: "A Swin Transformer model for classifying 10,216 white blood cell images into Normal and Chronic Lymphocytic Leukemia (CLL), achieving 86.96% accuracy and deployed through an interactive Streamlit application.",
      },
      context: {
        id: "Project berfokus pada klasifikasi citra sel darah putih menggunakan deep learning dan menyediakan hasil model melalui aplikasi web interaktif.",
        en: "The project focuses on white blood cell image classification using deep learning and makes the model available through an interactive web application.",
      },
      problem: null,
      goals: {
        id: [
          "Mengklasifikasikan citra sel darah putih menjadi kelas Normal dan Chronic Lymphocytic Leukemia.",
          "Melakukan preprocessing, hyperparameter tuning, dan evaluasi model.",
          "Menyediakan model melalui aplikasi Streamlit yang interaktif.",
        ],
        en: [
          "Classify white blood cell images into Normal and Chronic Lymphocytic Leukemia classes.",
          "Perform preprocessing, hyperparameter tuning, and model evaluation.",
          "Deliver the model through an interactive Streamlit application.",
        ],
      },
      constraints: { id: [], en: [] },
      solution: {
        id: "Mengembangkan model Swin Transformer, menjalankan preprocessing dan hyperparameter tuning, mengevaluasi performa klasifikasi, lalu mengintegrasikan model ke aplikasi Streamlit.",
        en: "Developed a Swin Transformer model, performed preprocessing and hyperparameter tuning, evaluated classification performance, and integrated the model into a Streamlit application.",
      },
      architecture: {
        id: "Alur project mencakup preprocessing citra, model Swin Transformer, evaluasi klasifikasi, dan aplikasi Streamlit sebagai layer interaksi pengguna.",
        en: "The project flow covers image preprocessing, a Swin Transformer model, classification evaluation, and a Streamlit application as the user interaction layer.",
      },
      implementation: {
        id: "Model dikembangkan untuk 10.216 citra sel darah putih dan mencakup preprocessing, hyperparameter tuning, evaluasi performa, serta deployment pada aplikasi Streamlit interaktif.",
        en: "The model was developed for 10,216 white blood cell images and included preprocessing, hyperparameter tuning, performance evaluation, and deployment in an interactive Streamlit application.",
      },
      engineeringDecisions: {
        id: ["Menggunakan Swin Transformer sebagai arsitektur klasifikasi citra.", "Menggunakan Streamlit untuk menyediakan interface interaktif bagi model."],
        en: ["Used Swin Transformer as the image-classification architecture.", "Used Streamlit to provide an interactive interface for the model."],
      },
      dataFlow: {
        id: "Citra sel darah putih diproses melalui tahap preprocessing sebelum diteruskan ke model Swin Transformer; hasil klasifikasi kemudian disajikan pada aplikasi Streamlit.",
        en: "White blood cell images pass through preprocessing before being processed by the Swin Transformer model; classification results are then presented in the Streamlit application.",
      },
      accessibility: null,
      seo: null,
      performance: null,
      challenges: { id: [], en: [] },
      tradeoffs: { id: [], en: [] },
      results: {
        id: "Model mencapai akurasi 86,96% pada klasifikasi Normal dan CLL dan telah di-deploy pada aplikasi Streamlit interaktif.",
        en: "The model achieved 86.96% accuracy for Normal and CLL classification and was deployed in an interactive Streamlit application.",
      },
      measurableOutcomes: {
        id: ["10.216 citra sel darah putih", "Akurasi 86,96%"],
        en: ["10,216 white blood cell images", "86.96% accuracy"],
      },
      lessonsLearned: { id: [], en: [] },
    },
  },
  {
    slug: "employee-attendance-system",
    placeholder: false,
    title: { id: "Employee Attendance System", en: "Employee Attendance System" },
    shortTitle: { id: "Attendance System", en: "Attendance System" },
    year: "2025",
    startDate: "2025-02",
    endDate: "2025-07",
    status: { id: "Selesai", en: "Completed" },
    featured: true,
    role: { id: "Full Stack Developer", en: "Full Stack Developer" },
    projectType: { id: "Aplikasi Web", en: "Web Application" },
    teamContext: { id: "Project di PT. Winnicode Garuda Teknologi", en: "Project at PT. Winnicode Garuda Teknologi" },
    company: "PT. Winnicode Garuda Teknologi",
    client: null,
    links: { liveUrl: null, repositoryUrl: null, documentationUrl: null },
    technology: {
      stack: ["Laravel", "MySQL"],
      tools: ["Software Testing"],
    },
    media: {
      cover: "/image/mockup absen.png",
      thumbnail: "/image/thumbnail absen.png",
      coverAlt: {
        id: "Visual placeholder untuk Employee Attendance System.",
        en: "Visual placeholder for the Employee Attendance System.",
      },
      screenshots: [],
      gallery: [],
      ogImage: null,
    },
    caseStudy: {
      summary: {
        id: "Aplikasi attendance berbasis web untuk 50+ karyawan dengan authentication, clock-in/clock-out, attendance summary, dan database MySQL yang menangani ratusan record.",
        en: "A web-based attendance application for 50+ employees with authentication, clock-in/clock-out, attendance summaries, and a MySQL database handling hundreds of records.",
      },
      context: {
        id: "Project dikembangkan di PT. Winnicode Garuda Teknologi untuk mendukung pencatatan dan pengelolaan attendance karyawan secara terintegrasi.",
        en: "The project was developed at PT. Winnicode Garuda Teknologi to support integrated employee attendance recording and management.",
      },
      problem: null,
      goals: {
        id: ["Mendukung proses attendance untuk 50+ karyawan.", "Menyediakan authentication dan workflow clock-in/clock-out.", "Menyajikan attendance summary dari data yang tersimpan di MySQL."],
        en: ["Support attendance workflows for 50+ employees.", "Provide authentication and clock-in/clock-out workflows.", "Present attendance summaries from data stored in MySQL."],
      },
      constraints: { id: [], en: [] },
      solution: {
        id: "Mengembangkan aplikasi attendance berbasis Laravel dan MySQL yang menggabungkan authentication, clock-in/clock-out, attendance summary, serta pengelolaan data dalam satu sistem.",
        en: "Developed a Laravel and MySQL attendance application combining authentication, clock-in/clock-out, attendance summaries, and data management in a single system.",
      },
      architecture: {
        id: "Aplikasi web menggunakan Laravel untuk application logic dan MySQL untuk penyimpanan serta pengelolaan data attendance.",
        en: "The web application uses Laravel for application logic and MySQL for attendance data storage and management.",
      },
      implementation: {
        id: "Implementasi mencakup authentication, clock-in/clock-out, attendance summary, pengelolaan database yang menangani ratusan record, serta testing dan maintenance untuk menjaga keandalan operasi.",
        en: "Implementation covered authentication, clock-in/clock-out, attendance summaries, database management handling hundreds of records, plus testing and maintenance to support reliable operation.",
      },
      engineeringDecisions: { id: [], en: [] },
      dataFlow: {
        id: "Aktivitas clock-in/clock-out pengguna diproses oleh aplikasi dan disimpan di MySQL, kemudian data tersebut digunakan untuk membentuk ringkasan attendance.",
        en: "Employee clock-in/clock-out activity is processed by the application and stored in MySQL, then used to generate attendance summaries.",
      },
      accessibility: null,
      seo: null,
      performance: null,
      challenges: { id: [], en: [] },
      tradeoffs: { id: [], en: [] },
      results: {
        id: "Sistem mendukung 50+ karyawan dan mengelola ratusan record attendance, disertai testing dan maintenance untuk mendukung operasi yang andal.",
        en: "The system supports 50+ employees and manages hundreds of attendance records, with testing and maintenance performed to support reliable operation.",
      },
      measurableOutcomes: {
        id: ["50+ karyawan", "Ratusan record attendance"],
        en: ["50+ employees", "Hundreds of attendance records"],
      },
      lessonsLearned: { id: [], en: [] },
    },
  },
  {
    slug: "wiserrapp-swiftlet-farming",
    placeholder: false,
    title: {
      id: "WiserrApp for Swiftlet Farming",
      en: "WiserrApp for Swiftlet Farming",
    },
    shortTitle: { id: "WiserrApp", en: "WiserrApp" },
    year: "2024",
    startDate: "2024-09",
    endDate: "2024-09",
    status: { id: "Selesai", en: "Completed" },
    featured: true,
    role: { id: "Mobile Developer", en: "Mobile Developer" },
    projectType: { id: "Aplikasi Android", en: "Android Mobile Application" },
    teamContext: null,
    company: null,
    client: null,
    links: { liveUrl: null, repositoryUrl: null, documentationUrl: null },
    technology: {
      stack: ["Kotlin", "Jetpack Compose", "Dialogflow", "Firebase"],
      tools: [],
    },
    media: {
      cover: "/image/mockup wiser.png",
      thumbnail: "/image/thumbnail wiser.png",
      coverAlt: {
        id: "Visual placeholder untuk project WiserrApp for Swiftlet Farming.",
        en: "Visual placeholder for the WiserrApp for Swiftlet Farming project.",
      },
      screenshots: [],
      gallery: [],
      ogImage: null,
    },
    caseStudy: {
      summary: {
        id: "Aplikasi Android untuk manajemen budidaya walet dengan 6+ fitur utama, integrasi Dialogflow AI Chatbot dan Firebase, serta modul komunitas dan edukasi.",
        en: "An Android application for swiftlet farming management with 6+ key features, Dialogflow AI Chatbot and Firebase integration, plus community and educational modules.",
      },
      context: {
        id: "WiserrApp dikembangkan sebagai aplikasi Android untuk mendukung pengelolaan kegiatan budidaya walet melalui fitur konsultasi, notifikasi, data realtime, komunitas, dan edukasi.",
        en: "WiserrApp was developed as an Android application supporting swiftlet farming management through consultation, notifications, real-time data, community, and educational features.",
      },
      problem: null,
      goals: {
        id: ["Menyediakan 6+ fitur utama untuk kebutuhan pengelolaan budidaya walet.", "Mengintegrasikan konsultasi interaktif melalui Dialogflow AI Chatbot.", "Menggunakan Firebase untuk notifikasi dan data realtime.", "Menyediakan modul komunitas dan edukasi berupa video, artikel, dan kuis."],
        en: ["Provide 6+ key features for swiftlet farming management.", "Integrate interactive consultation through Dialogflow AI Chatbot.", "Use Firebase for notifications and real-time data.", "Provide community and educational modules with videos, articles, and quizzes."],
      },
      constraints: { id: [], en: [] },
      solution: {
        id: "Mengembangkan aplikasi Android menggunakan Kotlin dan Jetpack Compose, mengintegrasikan Dialogflow untuk chatbot serta Firebase untuk konsultasi, notifikasi, dan data realtime, ditambah modul komunitas dan edukasi.",
        en: "Developed an Android application using Kotlin and Jetpack Compose, integrating Dialogflow for the chatbot and Firebase for consultations, notifications, and real-time data, plus community and educational modules.",
      },
      architecture: {
        id: "Aplikasi Android dibangun dengan Kotlin dan Jetpack Compose, terintegrasi dengan Dialogflow dan Firebase untuk fitur chatbot, notifikasi, serta data realtime.",
        en: "The Android application is built with Kotlin and Jetpack Compose and integrates Dialogflow and Firebase for chatbot, notification, and real-time data features.",
      },
      implementation: {
        id: "Implementasi menghasilkan 6+ fitur utama dan mencakup konsultasi interaktif, notifikasi, data realtime, komunitas, video, artikel, serta kuis edukasi.",
        en: "Implementation delivered 6+ key features covering interactive consultation, notifications, real-time data, community, videos, articles, and educational quizzes.",
      },
      engineeringDecisions: {
        id: ["Menggunakan Jetpack Compose untuk Android UI.", "Menggunakan Dialogflow untuk AI chatbot.", "Menggunakan Firebase untuk notifikasi dan data realtime."],
        en: ["Used Jetpack Compose for the Android UI.", "Used Dialogflow for the AI chatbot.", "Used Firebase for notifications and real-time data."],
      },
      dataFlow: {
        id: "Aplikasi Android berinteraksi dengan Firebase untuk data realtime dan notifikasi, sedangkan konsultasi chatbot ditangani melalui integrasi Dialogflow.",
        en: "The Android application interacts with Firebase for real-time data and notifications, while chatbot consultations are handled through Dialogflow integration.",
      },
      accessibility: null,
      seo: null,
      performance: null,
      challenges: { id: [], en: [] },
      tradeoffs: { id: [], en: [] },
      results: {
        id: "Aplikasi menyediakan 6+ fitur utama dan menggabungkan konsultasi AI, notifikasi, data realtime, komunitas, serta konten edukasi dalam satu aplikasi Android.",
        en: "The application provides 6+ key features and combines AI consultation, notifications, real-time data, community, and educational content in one Android application.",
      },
      measurableOutcomes: { id: ["6+ fitur utama"], en: ["6+ key features"] },
      lessonsLearned: { id: [], en: [] },
    },
  },
];
